server:
  port: 5489

spring:
  datasource:
    url: jdbc:mysql://localhost:4000/tx?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  application:
    name: DEMO
  http:
    encoding:
      charset: UTF-8
  rabbitmq:
    host: 192.168.198.131
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

mybatis:
  mapper-locations: classpath:mapper/*.xml